### ISSUE TITLE
Overwriting of Variable BOOTSPEC_OPTIONS[doc] ?

### ISSUE THREAD

**Issue by EugenWiens** [pengutronix/meta-ptx#12]
In file `meta-ptx/classes/bootspec.bbclass` in Line 33 the Variable `BOOTSPEC_OPTIONS[doc]` is set and in Line 36 is an set again. Should it be an append ?

![image](https://user-images.githubusercontent.com/7880602/44896506-b8f91a80-acf8-11e8-9ada-0ff7607cff54.png)

**Comment by ejoerns** [comment]
Good catch, it should be

``` patch
 BOOTSPEC_EXTRALINE ?= ""
-BOOTSPEC_OPTIONS[doc] = "Allows to add extra content to bootspec entries, lines must be terminated with a newline"
+BOOTSPEC_EXTRALINE[doc] = "Allows to add extra content to bootspec entries, lines must be terminated with a newline"
```

Would you like to make a patch? ;)
