### ISSUE TITLE
Rootfs image name

### ISSUE THREAD

**Issue by thburghout** [pengutronix/meta-ptx#124]
Hi,

I was updating our layers, and I ran into an issue with an incorrect filename passed to `tar`.

```
| NOTE: Unpacking /home/user/Documents/foo/build/tmp-glibc/deploy/images/nedap-foo/foo-base-nedap-foo.tar.bz2 to /home/user/Documents/foo/build/tmp-glibc/work/nedap_foo-oe-linux-gnueabi/foo-image/1.0/root
| tar: /home/user/Documents/foo/build/tmp-glibc/deploy/images/nedap-foo/foo-base-nedap-foo.tar.bz2: Cannot open: No such file or directory
| tar: Error is not recoverable: exiting now
```

I believe this is due to naming convention change in 4.3 https://docs.yoctoproject.org/singleindex.html#output-file-naming-changes . 

The image is now named `foo-base-nedap-foo.rootfs.tar.bz2` (recipe `foo-base`, machine `nedap-foo`). Note the addition of `.rootfs`.

I could work around this by setting 

```
GENIMAGE_ROOTFS_IMAGE_FSTYPE = "rootfs.tar.bz2"
```

in my image recipe. However, I am not sure that this is an appropriate fix. 

If there is more information needed, please let me know.

Thanks!

**Comment by Bastian-Krause** [comment]
See #123.

**Comment by thburghout** [comment]
Apologies, I forgot to take a look at the pull request. Thank you!
