### ISSUE TITLE
cannot be compatible with both scarthgap and nanbield

### ISSUE THREAD

**Issue by Villemoes** [pengutronix/meta-ptx#131]
OE-core has renamed the bmap-tools recipe to bmaptool, so now one gets

    ERROR: Nothing PROVIDES 'bmap-tools-native'. Close matches:
      bmaptool-native
      bpftool-native
      mtools-native

They refuse to add the PROVIDES which would give compatibility

https://lore.kernel.org/openembedded-core/CANNYZj_5AkKa_dJVmjzvnng_7SFrdDr70T_wDN=bcA2WfMX+Bw@mail.gmail.com/
https://lore.kernel.org/openembedded-core/ba338ad83d02efbaeac55e4f80d9560cab92a54d.camel@linuxfoundation.org/

I don't really see any way to actually keep meta-ptx compatible with both nanbield and scarthgap (of course, this particular thing is only an issue when one sets GENIMAGE_CREATE_BMAP).

**Comment by ejoerns** [comment]
I see no need to keep `master`/`scarthgap` compatible with `nanbield`.

Thus we can refer to the new name and remove compatibility to `nanbield`.
