### ISSUE TITLE
libconfuse patch dropped

### ISSUE THREAD

**Issue by hoyes** [pengutronix/meta-ptx#143]
With meta-ptx master I am seeing the following error when using the genimage bbclass:

`ERROR: could not open config file '[REDACTED]/.config'`

, even though the path exists.

I think this is because the downstream patch was dropped when upgrading from confuse 3.2.2 to confuse 3.3, even though this fix isn't yet included in a confuse release.

**Comment by ejoerns** [comment]
@hoyes Thanks for the hint, I was quite sure having checked it is part of v3.3 already, but maybe got confused by the GitHub UI somewhere. It is actually part of master but not part of v3.3. I hope there will be a v3.4 some day.

Would you like to make a PR to re-add it? Or should I?

**Comment by hoyes** [comment]
Yea a confuse v3.4 would be ideal.

Please could you do the PR in this instance? I have just started the internal process at Arm so we can contribute to meta-ptx in the future, but this will take a week or so.

**Comment by ejoerns** [comment]
@hoyes FTR: I've created #144 to fix it.

Btw. the 'secret' plan behind `meta-ptx` is to contribute its pieces to 'standard' layers step by step. But let's see how realistic this is.. :smirk:
