### ISSUE TITLE
genimage bug fix on dunfell branch

### ISSUE THREAD

**Issue by gdoffe** [pengutronix/meta-ptx#89]
Hi,

Do you think it could make sense to cherry-pick this fix https://github.com/pengutronix/meta-ptx/commit/73c3252f86fe2889687cc026b00836bbd1a4adce on the dunfell branch as it is a long term support branch and this is a bug fix ?

Gilles

**Comment by ejoerns** [comment]
Yes, it should be in 'dunfell', too. I am currently picking a few other candidates and will update dunfell then.

**Comment by ejoerns** [comment]
I've applied this to dunfell now. Case closed.

**Comment by gdoffe** [comment]
Thank you Enrico. :+1:
